import {
  APGCase,
  AppSettings,
  BaremaCriterion,
  Class,
  ClassGroup,
  Evaluation,
  SOI,
  Semester,
  Student,
  TableAllocation,
  TableAllocationChangeLog,
} from '../types';

export const initialBaremaCriteria: BaremaCriterion[] = [
  {
    id: 'crit_1',
    name: 'Abertura e integração',
    maxScore: 5,
    description: 'Pontualidade, apresentação do caso, empatia e clima grupal acolhedor.',
  },
  {
    id: 'crit_2',
    name: 'Postura ético-profissional e colaboração',
    maxScore: 5,
    description: 'Escuta ativa, respeito às opiniões, divisão justa das tarefas e ética.',
  },
  {
    id: 'crit_3',
    name: 'Desempenho técnico e acadêmico',
    maxScore: 5,
    description: 'Domínio dos objetivos, embasamento fisiopatológico e clareza argumentativa.',
  },
  {
    id: 'crit_4',
    name: 'Fechamento e síntese',
    maxScore: 5,
    description: 'Capacidade de resumo dos aprendizados, autoavaliação e identificação de lacunas.',
  },
];

export const initialSemesters: Semester[] = [];
export const initialSOIs: SOI[] = [];

export const initialClasses: Class[] = [
  {
    id: 'cls_med_1',
    name: 'Medicina 2026.1 - APG I',
    semesterId: 'sem_2026_1',
    yearSemester: '2026.1',
    responsibleTeacher: 'Docente não identificado',
  },
  {
    id: 'cls_med_2',
    name: 'Medicina 2026.1 - APG II',
    semesterId: 'sem_2026_1',
    yearSemester: '2026.1',
    responsibleTeacher: 'Profa. Dra. Mariana Souza',
  },
];

export const initialGroups: ClassGroup[] = [
  { id: 'grp_m1_c1', name: 'Mesa 1', classId: 'cls_med_1', limitStudents: 10 },
  { id: 'grp_m2_c1', name: 'Mesa 2', classId: 'cls_med_1', limitStudents: 10 },
  { id: 'grp_m3_c1', name: 'Mesa 3', classId: 'cls_med_1', limitStudents: 10 },
  { id: 'grp_m1_c2', name: 'Mesa 1', classId: 'cls_med_2', limitStudents: 10 },
  { id: 'grp_m2_c2', name: 'Mesa 2', classId: 'cls_med_2', limitStudents: 10 },
  { id: 'grp_m3_c2', name: 'Mesa 3', classId: 'cls_med_2', limitStudents: 10 },
];

export const initialStudents: Student[] = [
  {
    id: 'std_1',
    name: 'Ana Beatris Silva',
    enrollment: '20241011',
    classId: 'cls_med_1',
    groupId: 'grp_m1_c1',
    email: 'ana.beatris@med.edu.br',
    status: 'Ativo',
    notes: 'Excelente oratória e raciocínio clínico aguçado.',
  },
  {
    id: 'std_2',
    name: 'Bruno Gabriel Oliveira',
    enrollment: '20241012',
    classId: 'cls_med_1',
    groupId: 'grp_m1_c1',
    email: 'bruno.gabriel@med.edu.br',
    status: 'Ativo',
  },
  {
    id: 'std_3',
    name: 'Carla Vasconcelos',
    enrollment: '20241013',
    classId: 'cls_med_1',
    groupId: 'grp_m2_c1',
    email: 'carla.v@med.edu.br',
    status: 'Atenção',
    notes: 'Dificuldades na síntese final do caso.',
  },
  {
    id: 'std_4',
    name: 'Diego Fernandes',
    enrollment: '20241014',
    classId: 'cls_med_1',
    groupId: 'grp_m1_c1',
    email: 'diego.f@med.edu.br',
    status: 'Ativo',
  },
  {
    id: 'std_5',
    name: 'Eduarda Lima',
    enrollment: '20241015',
    classId: 'cls_med_1',
    groupId: 'grp_m2_c1',
    email: 'eduarda.lima@med.edu.br',
    status: 'Ativo',
  },
  {
    id: 'std_6',
    name: 'Felipe Martins',
    enrollment: '20241016',
    classId: 'cls_med_1',
    groupId: 'grp_m3_c1',
    email: 'felipe.martins@med.edu.br',
    status: 'Ativo',
  },
  {
    id: 'std_7',
    name: 'Gabriela Ramos',
    enrollment: '20241017',
    classId: 'cls_med_1',
    groupId: 'grp_m3_c1',
    email: 'gabriela.r@med.edu.br',
    status: 'Ativo',
  },
  {
    id: 'std_8',
    name: 'Henrique Alves',
    enrollment: '20241018',
    classId: 'cls_med_1',
    groupId: 'grp_m2_c1',
    email: 'henrique.a@med.edu.br',
    status: 'Atenção',
    notes: 'Possui faltas sem atestado justificativo.',
  },
  {
    id: 'std_9',
    name: 'Isabela Costa',
    enrollment: '20241019',
    classId: 'cls_med_1',
    groupId: 'grp_m2_c1',
    email: 'isabela.c@med.edu.br',
    status: 'Ativo',
  },
  {
    id: 'std_10',
    name: 'João Pedro Rocha',
    enrollment: '20241020',
    classId: 'cls_med_1',
    groupId: 'grp_m3_c1',
    email: 'joao.rocha@med.edu.br',
    status: 'Ativo',
  },
  {
    id: 'std_11',
    name: 'Lucas Ferreira',
    enrollment: '20241021',
    classId: 'cls_med_2',
    groupId: 'grp_m1_c2',
    email: 'lucas.f@med.edu.br',
    status: 'Ativo',
  },
  {
    id: 'std_12',
    name: 'Mariana Duarte',
    enrollment: '20241022',
    classId: 'cls_med_2',
    groupId: 'grp_m2_c2',
    email: 'mariana.d@med.edu.br',
    status: 'Ativo',
  },
];

export const initialTableAllocations: TableAllocation[] = [
  // Class 1 - Unit 1 Allocations (Weeks 1 to 8)
  { id: 'alloc_1_u1', studentId: 'std_1', classId: 'cls_med_1', groupId: 'grp_m1_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_2_u1', studentId: 'std_2', classId: 'cls_med_1', groupId: 'grp_m1_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_3_u1', studentId: 'std_3', classId: 'cls_med_1', groupId: 'grp_m2_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_4_u1', studentId: 'std_4', classId: 'cls_med_1', groupId: 'grp_m1_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_5_u1', studentId: 'std_5', classId: 'cls_med_1', groupId: 'grp_m2_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_6_u1', studentId: 'std_6', classId: 'cls_med_1', groupId: 'grp_m3_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_7_u1', studentId: 'std_7', classId: 'cls_med_1', groupId: 'grp_m3_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_8_u1', studentId: 'std_8', classId: 'cls_med_1', groupId: 'grp_m2_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_9_u1', studentId: 'std_9', classId: 'cls_med_1', groupId: 'grp_m2_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_10_u1', studentId: 'std_10', classId: 'cls_med_1', groupId: 'grp_m3_c1', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },

  // Class 1 - Unit 2 Allocations (Weeks 9 to 20)
  // Example 1: Ana (std_1) moved from Mesa 1 to Mesa 3
  { id: 'alloc_1_u2', studentId: 'std_1', classId: 'cls_med_1', groupId: 'grp_m3_c1', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' },
  // Example 2: Bruno (std_2) stayed in Mesa 1
  { id: 'alloc_2_u2', studentId: 'std_2', classId: 'cls_med_1', groupId: 'grp_m1_c1', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' },
  // Example 3: Carla (std_3) pending / not defined yet for Unit 2 (no record)
  { id: 'alloc_4_u2', studentId: 'std_4', classId: 'cls_med_1', groupId: 'grp_m1_c1', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' },
  { id: 'alloc_5_u2', studentId: 'std_5', classId: 'cls_med_1', groupId: 'grp_m2_c1', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' },
  { id: 'alloc_6_u2', studentId: 'std_6', classId: 'cls_med_1', groupId: 'grp_m2_c1', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' }, // Moved Mesa 3 -> Mesa 2
  { id: 'alloc_7_u2', studentId: 'std_7', classId: 'cls_med_1', groupId: 'grp_m3_c1', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' },
  { id: 'alloc_8_u2', studentId: 'std_8', classId: 'cls_med_1', groupId: 'grp_m3_c1', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' }, // Moved Mesa 2 -> Mesa 3
  { id: 'alloc_9_u2', studentId: 'std_9', classId: 'cls_med_1', groupId: 'grp_m2_c1', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' },
  { id: 'alloc_10_u2', studentId: 'std_10', classId: 'cls_med_1', groupId: 'grp_m1_c1', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' }, // Moved Mesa 3 -> Mesa 1

  // Class 2 Allocations
  { id: 'alloc_11_u1', studentId: 'std_11', classId: 'cls_med_2', groupId: 'grp_m1_c2', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_12_u1', studentId: 'std_12', classId: 'cls_med_2', groupId: 'grp_m2_c2', unit: 1, startDate: '2026-02-02', createdAt: '2026-02-02', updatedAt: '2026-02-02' },
  { id: 'alloc_11_u2', studentId: 'std_11', classId: 'cls_med_2', groupId: 'grp_m1_c2', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' },
  { id: 'alloc_12_u2', studentId: 'std_12', classId: 'cls_med_2', groupId: 'grp_m2_c2', unit: 2, startDate: '2026-03-30', createdAt: '2026-03-30', updatedAt: '2026-03-30' },
];

export const initialTableAllocationLogs: TableAllocationChangeLog[] = [
  {
    id: 'log_1',
    studentId: 'std_1',
    classId: 'cls_med_1',
    previousGroupId: 'grp_m1_c1',
    newGroupId: 'grp_m3_c1',
    unit: 2,
    date: '2026-03-30 09:15',
    changedBy: 'Coordenador APG',
  },
  {
    id: 'log_2',
    studentId: 'std_6',
    classId: 'cls_med_1',
    previousGroupId: 'grp_m3_c1',
    newGroupId: 'grp_m2_c1',
    unit: 2,
    date: '2026-03-30 09:20',
    changedBy: 'Coordenador APG',
  },
  {
    id: 'log_3',
    studentId: 'std_8',
    classId: 'cls_med_1',
    previousGroupId: 'grp_m2_c1',
    newGroupId: 'grp_m3_c1',
    unit: 2,
    date: '2026-03-30 09:22',
    changedBy: 'Coordenador APG',
  },
];


// Generate 20 APG weeks with both Case 1 and Case 2
export const initialAPGCases: APGCase[] = [
  // SEMANA 1
  {
    id: 'case_w1',
    caseNumber: 1,
    problemNumber: 1,
    week: 1,
    unit: 1,
    title: 'Dispneia Aguda no Idoso',
    theme: 'Sistema Cardiorrespiratório',
    date: '2026-02-09',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Paciente de 68 anos, hipertenso, dá entrada com dispneia progressiva e edema de membros inferiores.',
    learningObjectives: [
      'Compreender os mecanismos fisiopatológicos da Insuficiência Cardíaca Congestiva.',
      'Identificar sinais semiológicos de congestão pulmonar e sistêmica.',
      'Diferenciar dispneia cardíaca de causas pulmonares.',
    ],
    teacherInstructions: 'Estimular a discussão sobre fisiopatologia cardíaca e uso de diuréticos.',
    status: 'realizado',
  },
  {
    id: 'case_w1_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 1,
    unit: 1,
    title: 'Insuficiência Cardíaca Descompensada',
    theme: 'Sistema Cardiorrespiratório - Terapêutica',
    date: '2026-02-11',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Fechamento do caso de IC: discussão terapêutica, drogas vasoativas e manejo ambulatorial pós-alta.',
    learningObjectives: [
      'Estruturar plano terapêutico para IC com fração de ejeção reduzida.',
      'Interpretar exames complementares (BNP, ecocardiograma, radiografia de tórax).',
      'Elaborar orientações de autocuidado e controle de volemia.',
    ],
    teacherInstructions: 'Avaliar a fundamentação das condutas farmacológicas.',
    status: 'realizado',
  },

  // SEMANA 2
  {
    id: 'case_w2',
    caseNumber: 1,
    problemNumber: 1,
    week: 2,
    unit: 1,
    title: 'Cefaleia e Sinais Meníngeos',
    theme: 'Infectologia / Neurologia',
    date: '2026-02-16',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Jovem de 22 anos apresenta febre alta, rigidez de nuca e fotofobia há 24 horas.',
    learningObjectives: [
      'Estudar etiologia das meningites bacterianas e virais.',
      'Avaliar exames de imagem e líquor.',
      'Indicar antibioticoterapia empírica imediata.',
    ],
    teacherInstructions: 'Cobrar diagnóstico diferencial rigoroso.',
    status: 'realizado',
  },
  {
    id: 'case_w2_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 2,
    unit: 1,
    title: 'Meningite Bacteriana e Terapêutica',
    theme: 'Infectologia / Neurologia - Conduta',
    date: '2026-02-18',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Análise dos resultados do líquor (pleocitose neutrofílica, hiperproteinorraquia) e profilaxia de contatos.',
    learningObjectives: [
      'Interpretar o padrão liquórico nas meningites agudas.',
      'Definir esquemas antimicrobianos e corticoterapia adjunta.',
      'Conhecer medidas de vigilância epidemiológica e quimioprofilaxia.',
    ],
    teacherInstructions: 'Focar na quimioprofilaxia de comunicantes próximos.',
    status: 'realizado',
  },

  // SEMANA 3
  {
    id: 'case_w3',
    caseNumber: 1,
    problemNumber: 1,
    week: 3,
    unit: 1,
    title: 'Dor Abdominal Aguda em Fossa Ilíaca Direita',
    theme: 'Gastroenterologia / Cirurgia',
    date: '2026-02-23',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Estudante de 19 anos com dor periumbilical que migrou para FID, associada a náuseas e febre baixa.',
    learningObjectives: [
      'Analisar a fisiopatologia da apendicite aguda.',
      'Interpretar escores clínicos (Alvarado).',
      'Discutir conduta cirúrgica e exames complementares.',
    ],
    teacherInstructions: 'Discutir diagnósticos diferenciais ginecológicos em mulheres.',
    status: 'realizado',
  },
  {
    id: 'case_w3_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 3,
    unit: 1,
    title: 'Abdome Agudo Inflamatório e Conduta',
    theme: 'Cirurgia Geral / Emergência',
    date: '2026-02-25',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Fechamento sobre apendicite aguda perfurada versus não-perfurada, antibioticoprofilaxia e pós-operatório.',
    learningObjectives: [
      'Comparar abordagem laparoscópica e laparotômica.',
      'Manejar complicações pós-operatórias precoces.',
      'Revisar antibióticos em infecções intra-abdominais.',
    ],
    teacherInstructions: 'Estimular debate sobre apendicectomia de urgência.',
    status: 'realizado',
  },

  // SEMANA 4
  {
    id: 'case_w4',
    caseNumber: 1,
    problemNumber: 1,
    week: 4,
    unit: 1,
    title: 'Polidipsia, Poliúria e Perda de Peso',
    theme: 'Endocrinologia',
    date: '2026-03-02',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Adolescente de 14 anos com perda involuntária de 6 kg, astenia e hálito cetônico.',
    learningObjectives: [
      'Diferenciar Diabetes Mellitus Tipo 1 e Tipo 2.',
      'Compreender a cetoacidose diabética e manejo de insulina.',
      'Discutir adesão ao tratamento na adolescência.',
    ],
    teacherInstructions: 'Focar na fisiopatologia da deficiência absoluta de insulina.',
    status: 'realizado',
  },
  {
    id: 'case_w4_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 4,
    unit: 1,
    title: 'Cetoacidose Diabética e Insulinoterapia',
    theme: 'Endocrinologia / Emergência',
    date: '2026-03-04',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Fechamento do protocolo de hidratação venosa, correção de potássio e bomba de insulina em CAD.',
    learningObjectives: [
      'Calcular o ânion gap e reposição de potássio na CAD.',
      'Prescrever esquemas de insulinoterapia basal-bolus.',
      'Orientar prevenção de episódios recorrentes de cetoacidose.',
    ],
    teacherInstructions: 'Cobrar domínio dos critérios de resolução da CAD.',
    status: 'realizado',
  },

  // SEMANA 5
  {
    id: 'case_w5',
    caseNumber: 1,
    problemNumber: 1,
    week: 5,
    unit: 1,
    title: 'Fraqueza Muscular e Anemia',
    theme: 'Hematologia',
    date: '2026-03-09',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Mulher de 34 anos com parestesias, glossite e fadiga crônica.',
    learningObjectives: [
      'Classificar anemias microcíticas e macrocíticas.',
      'Estudar o metabolismo da Vitamina B12 e Ácido Fólico.',
    ],
    teacherInstructions: 'Solicitar avaliação de hemograma completo.',
    status: 'realizado',
  },
  {
    id: 'case_w5_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 5,
    unit: 1,
    title: 'Anemias Megaloblástica e Carenciais',
    theme: 'Hematologia Clínica',
    date: '2026-03-11',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Diferenciação laboratorial entre carência de B12 e folato, teste de Schilling e reposição parenteral.',
    learningObjectives: [
      'Interpretar dosagens de ácido metilmalônico e homocisteína.',
      'Identificar manifestações neurológicas irreversíveis da deficiência de B12.',
      'Prescrever a reposição vitamínica adequada.',
    ],
    teacherInstructions: 'Enfatizar as consequências neurológicas.',
    status: 'realizado',
  },

  // SEMANA 6
  {
    id: 'case_w6',
    caseNumber: 1,
    problemNumber: 1,
    week: 6,
    unit: 1,
    title: 'Icterícia e Colúria',
    theme: 'Hepatologia',
    date: '2026-03-16',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Homem de 45 anos apresenta icterícia, febre, acolia fecal e prurido corporal.',
    learningObjectives: [
      'Analisar o metabolismo da bilirrubina.',
      'Diferenciar icterícias pré-hepáticas, hepáticas e pós-hepáticas.',
    ],
    teacherInstructions: 'Reforçar exames de enzimas hepáticas e colestase.',
    status: 'realizado',
  },
  {
    id: 'case_w6_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 6,
    unit: 1,
    title: 'Síndromes Ictéricas e Colestase',
    theme: 'Gastroenterologia / Hepatologia',
    date: '2026-03-18',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Abordagem diagnóstica por imagem (ultrassonografia, CPRE, colangiorressonância) e desobstrução biliar.',
    learningObjectives: [
      'Interpretar padrão de colestase (FA, GGT, Bilirrubina Direta).',
      'Diferenciar coledocolitíase de neoplasias periampulares.',
      'Discutir indicação de drenagem biliar de urgência.',
    ],
    teacherInstructions: 'Revisar indicações de CPRE.',
    status: 'realizado',
  },

  // SEMANA 7
  {
    id: 'case_w7',
    caseNumber: 1,
    problemNumber: 1,
    week: 7,
    unit: 1,
    title: 'Crise Asmática Moderada',
    theme: 'Pneumologia',
    date: '2026-03-23',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Criança de 8 anos trazida ao pronto-socorro com sibilos expiratórios e tiragem intercostal.',
    learningObjectives: [
      'Entender a hiperresponsividade brônquica.',
      'Classificar a gravidade das exacerbações de asma.',
      'Manejar broncodilatadores e corticoides.',
    ],
    teacherInstructions: 'Revisar escores pediátricos de desconforto respiratório.',
    status: 'realizado',
  },
  {
    id: 'case_w7_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 7,
    unit: 1,
    title: 'Manejo da Asma e Controle Crônico',
    theme: 'Pneumologia Pediátrica',
    date: '2026-03-25',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Plano de ação para asma ambulatorial, classificação de controle (GINA) e dispositivos inalatórios.',
    learningObjectives: [
      'Dominar as etapas de tratamento profilático segundo GINA.',
      'Orientar o uso correto de espaçadores e bombinhas inalatórias.',
      'Reduzir fatores desencadeantes ambientais e ocupacionais.',
    ],
    teacherInstructions: 'Praticar orientação de dispositivos inalatórios.',
    status: 'realizado',
  },

  // SEMANA 8
  {
    id: 'case_w8',
    caseNumber: 1,
    problemNumber: 1,
    week: 8,
    unit: 1,
    title: 'SÍNTESE DA 1ª UNIDADE - Caso Clínico Integrador 1',
    theme: 'Integrador U1',
    date: '2026-03-30',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Caso integrador de urgência abrangendo conceitos clínicos da 1ª Unidade.',
    learningObjectives: [
      'Sintetizar diagnósticos diferenciais múltiplos.',
      'Demonstrar liderança e comunicação interpessoal eficientes.',
    ],
    teacherInstructions: 'Fechamento da 1ª Unidade.',
    status: 'planejado',
  },
  {
    id: 'case_w8_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 8,
    unit: 1,
    title: 'SÍNTESE DA 1ª UNIDADE - Caso Clínico Integrador 2',
    theme: 'Integrador U1 - Transição',
    date: '2026-04-01',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Sessão final da 1ª Unidade com autoavaliação, consolidação de notas e preparação para recomposição.',
    learningObjectives: [
      'Realizar autoavaliação crítica do desempenho longitudinal na U1.',
      'Receber feedback formativo global do tutor.',
      'Integrar novos membros para a 2ª Unidade.',
    ],
    teacherInstructions: 'Aplicar lembrete de recomposição das mesas.',
    status: 'planejado',
  },

  // SEMANA 9 (Início U2)
  {
    id: 'case_w9',
    caseNumber: 1,
    problemNumber: 1,
    week: 9,
    unit: 2,
    title: 'Síndrome Nefrótica em Criança',
    theme: 'Nefrologia (Início U2)',
    date: '2026-04-06',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Menino de 5 anos com edema periorbitário matutino, proteinúria maciça e hipoalbuminemia.',
    learningObjectives: [
      'Compreender a fisiopatologia da barreira de filtração glomerular.',
      'Diferenciar Síndrome Nefrótica de Nefrítica.',
    ],
    teacherInstructions: 'Primeiro caso da 2ª Unidade (Ajuste para nota final 15 pts).',
    status: 'realizado',
  },
  {
    id: 'case_w9_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 9,
    unit: 2,
    title: 'Glomerulopatias e Corticoterapia',
    theme: 'Nefrologia Pediátrica',
    date: '2026-04-08',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Discussão sobre Doença por Lesão Mínima, cortico-responsividade e prevenção de complicações trombóticas.',
    learningObjectives: [
      'Indicar biópsia renal nas glomerulopatias infantis.',
      'Manejar a corticoterapia e profilaxias infecciosas.',
      'Identificar sinais de trombose de veia renal.',
    ],
    teacherInstructions: 'Focar nos critérios de indicação de biópsia.',
    status: 'realizado',
  },

  // SEMANA 10
  {
    id: 'case_w10',
    caseNumber: 1,
    problemNumber: 1,
    week: 10,
    unit: 2,
    title: 'Hemiparesia e Afasia Súbita',
    theme: 'Neurologia Vascular',
    date: '2026-04-13',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Paciente de 62 anos chega com perda súbita de força no lado direito do corpo há 2 horas.',
    learningObjectives: [
      'Analisar os territórios vasculares cerebrais.',
      'Aplicações do escore NIHSS e protocolo de trombólise.',
    ],
    teacherInstructions: 'Discutir o conceito "tempo é cérebro".',
    status: 'realizado',
  },
  {
    id: 'case_w10_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 10,
    unit: 2,
    title: 'AVC Isquêmico: Trombólise e Trombectomia',
    theme: 'Neurologia Vascular / Emergência',
    date: '2026-04-15',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Fechamento sobre janela terapêutica no AVCi, critérios de exclusão para rtPA e reabilitação motora.',
    learningObjectives: [
      'Aplicar critérios de elegibilidade para trombólise química e mecânica.',
      'Manejar pressão arterial e controle glicêmico na fase aguda.',
      'Estruturar prevenção secundária (antiagregação vs anticoagulação).',
    ],
    teacherInstructions: 'Debater controle de PA nas primeiras 24 horas.',
    status: 'realizado',
  },

  // SEMANAS 11 a 20
  {
    id: 'case_w11',
    caseNumber: 1,
    problemNumber: 1,
    week: 11,
    unit: 2,
    title: 'Lúpus Eritematoso Sistêmico',
    theme: 'Reumatologia',
    date: '2026-04-20',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Mulher de 28 anos com artralgia, eritema malar, fotossensibilidade e alopecia.',
    learningObjectives: [
      'Estudar autoimunidade e imunocomplexos.',
      'Interpretar FAN, anti-DNA e fração de complemento.',
    ],
    teacherInstructions: 'Focar na nefrite lúpica.',
    status: 'realizado',
  },
  {
    id: 'case_w11_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 11,
    unit: 2,
    title: 'Nefrite Lúpica e Imunossupressão',
    theme: 'Reumatologia Avançada',
    date: '2026-04-22',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Classificação histopatológica da nefrite lúpica e terapias de indução com ciclofosfamida/micofenolato.',
    learningObjectives: [
      'Interpretar classes da nefrite lúpica (ISN/RPS).',
      'Monitorar atividade da doença pelo SLEDAI.',
      'Prescrever imunossupressores e hidroxicloroquina.',
    ],
    teacherInstructions: 'Acompanhar toxicidade ocular da hidroxicloroquina.',
    status: 'realizado',
  },

  {
    id: 'case_w12',
    caseNumber: 1,
    problemNumber: 1,
    week: 12,
    unit: 2,
    title: 'Depressão e Ideação Suicida na Atenção Primária',
    theme: 'Saúde Mental',
    date: '2026-04-27',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Paciente de 40 anos refere anedonia, insônia terminal e desânimo há 4 meses.',
    learningObjectives: [
      'Avaliar risco de suicídio na consulta médica.',
      'Conhecer mecanismos dos ISRS e psicoterapia.',
    ],
    teacherInstructions: 'Abordagem empática e ética em consulta delicada.',
    status: 'realizado',
  },
  {
    id: 'case_w12_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 12,
    unit: 2,
    title: 'Psicofarmacologia e Manejo de Crise',
    theme: 'Psiquiatria e Atenção Básica',
    date: '2026-04-29',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Escolha de antidepressivos conforme perfil de comorbidades, tempo de resposta e plano de segurança.',
    learningObjectives: [
      'Comparar perfis farmacocinéticos dos principais ISRS e IRSN.',
      'Reconhecer a síndrome serotoninérgica.',
      'Articular rede de atenção psicossocial (CAPS).',
    ],
    teacherInstructions: 'Enfatizar plano de segurança para ideação suicida.',
    status: 'realizado',
  },

  {
    id: 'case_w13',
    caseNumber: 1,
    problemNumber: 1,
    week: 13,
    unit: 2,
    title: 'Sepse de Foco Urinário',
    theme: 'Infectologia / Terapia Intensiva',
    date: '2026-05-04',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Idosa de 78 anos com rebaixamento do nível de consciência, hipotensão e disúria prévia.',
    learningObjectives: [
      'Definir Sepse e Choque Séptico (critérios qSOFA / SOFA).',
      'Aplicar o pacote de 1 hora da sepse.',
    ],
    teacherInstructions: 'Focar na ressuscitação volêmica precoce.',
    status: 'planejado',
  },
  {
    id: 'case_w13_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 13,
    unit: 2,
    title: 'Choque Séptico e Drogas Vasoativas',
    theme: 'Medicina Intensiva',
    date: '2026-05-06',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Manejo de noradrenalina, vasopressina, monitorização de lactato e controle de foco infeccioso.',
    learningObjectives: [
      'Titular drogas vasoativas guiadas por alvos hemodinâmicos (PAM >= 65).',
      'Interpretar o clearance de lactato como biomarcador de perfusão.',
      'Descalonar antibioticoterapia após culturas.',
    ],
    teacherInstructions: 'Cobrar protocolo de desmame de aminas.',
    status: 'planejado',
  },

  {
    id: 'case_w14',
    caseNumber: 1,
    problemNumber: 1,
    week: 14,
    unit: 2,
    title: 'Hipertireoidismo e Doença de Graves',
    theme: 'Endocrinologia II',
    date: '2026-05-11',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Mulher de 32 anos com tremores, perda de peso, taquicardia e exoftalmia bilateral.',
    learningObjectives: ['Compreender o eixo hipotálamo-hipófise-tireoide.', 'Avaliar anticorpos TRAB e anticorpos anti-TPO.'],
    teacherInstructions: 'Discutir opções terapêuticas antitireoidianas.',
    status: 'planejado',
  },
  {
    id: 'case_w14_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 14,
    unit: 2,
    title: 'Crise Tireotóxica e Terapia Definitiva',
    theme: 'Endocrinologia Avançada',
    date: '2026-05-13',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Manejo da tempestade tireoidiana (escore de Burch-Wartofsky), radioiodo e tireoidectomia.',
    learningObjectives: [
      'Aplicar o escore de Burch-Wartofsky para tempestade tireoidiana.',
      'Prescrever tionamidas, betabloqueadores e iodo inorgânico.',
      'Indicar radioablação vs cirurgia.',
    ],
    teacherInstructions: 'Revisar cuidados pré-operatórios no hipertireoidismo.',
    status: 'planejado',
  },

  {
    id: 'case_w15',
    caseNumber: 1,
    problemNumber: 1,
    week: 15,
    unit: 2,
    title: 'Fratura de Fêmur em Idoso Frágil',
    theme: 'Ortopedia e Geriatria',
    date: '2026-05-18',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Queda da própria altura em idosa de 82 anos, resultando em dor intensa na virilha e encurtamento do membro.',
    learningObjectives: ['Avaliar fragilidade óssea e osteoporose.', 'Abordagem multidisciplinar pré-operatória.'],
    teacherInstructions: 'Prevenção de quedas e reabilitação.',
    status: 'planejado',
  },
  {
    id: 'case_w15_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 15,
    unit: 2,
    title: 'Ortogeriatria e Prevenção de Quedas',
    theme: 'Geriatria e Reabilitação',
    date: '2026-05-20',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Prevenção de delirium pós-operatório, osteometabolismo (bisfosfonatos/teriparatida) e adaptação domiciliar.',
    learningObjectives: [
      'Prevenir e tratar delirium hospitalar.',
      'Instituir terapia anti-osteoporótica pós-fratura.',
      'Avaliar polifarmácia e sarcopenia.',
    ],
    teacherInstructions: 'Focar nos critérios de Beers para medicamentos inapropriados.',
    status: 'planejado',
  },

  {
    id: 'case_w16',
    caseNumber: 1,
    problemNumber: 1,
    week: 16,
    unit: 2,
    title: 'Intoxicação Exógena Aguda',
    theme: 'Toxicologia',
    date: '2026-05-25',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Paciente adentra sala de emergência com miose punctiforme, sialorreia e fasciculações.',
    learningObjectives: ['Reconhecer toxsíndromes (colinérgica, anticolinérgica, opioide).', 'Uso de antídotos específicos (atropina, pralidoxima).'],
    teacherInstructions: 'Treinar raciocínio rápido no pronto-socorro.',
    status: 'planejado',
  },
  {
    id: 'case_w16_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 16,
    unit: 2,
    title: 'Toxsíndromes e Descontaminação Gastrointestinal',
    theme: 'Toxicologia Médica',
    date: '2026-05-27',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Indicações de carvão ativado, lavagem gástrica, alcalinização urinária e suporte avançado de vida.',
    learningObjectives: [
      'Definir critérios rigorosos de indicação de lavagem gástrica.',
      'Prescrever antídotos específicos (N-acetilcisteína, naloxona, flumazenil).',
      'Articular suporte com o Centro de Informação Toxicológica (CIATox).',
    ],
    teacherInstructions: 'Revisar riscos da lavagem gástrica.',
    status: 'planejado',
  },

  {
    id: 'case_w17',
    caseNumber: 1,
    problemNumber: 1,
    week: 17,
    unit: 2,
    title: 'Pré-Eclâmpsia e Síndrome HELLP',
    theme: 'Ginecologia e Obstetrícia',
    date: '2026-06-01',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Gestante de 34 semanas com dor epigástrica, cefaleia e PA 170/110 mmHg.',
    learningObjectives: ['Identificar critérios de gravidade na pré-eclâmpsia.', 'Conduta no sulfato de magnésio.'],
    teacherInstructions: 'Enfocar na prevenção da eclampsia.',
    status: 'planejado',
  },
  {
    id: 'case_w17_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 17,
    unit: 2,
    title: 'Urgências Hipertensivas na Gestação e Parto',
    theme: 'Obstetrícia de Alto Risco',
    date: '2026-06-03',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Esquema de Zuspan/Pritchard com sulfato de magnésio, anti-hipertensivos parenterais e momento do parto.',
    learningObjectives: [
      'Dominar o esquema terapêutico do sulfato de magnésio e monitorar sinais de intoxicação (reflexo patelar, diurese).',
      'Prescrever hidralazina ou labetalol na crise hipertensiva gestacional.',
      'Definir a via de parto em pré-eclâmpsia grave.',
    ],
    teacherInstructions: 'Praticar o manejo do gluconato de cálcio como antídoto.',
    status: 'planejado',
  },

  {
    id: 'case_w18',
    caseNumber: 1,
    problemNumber: 1,
    week: 18,
    unit: 2,
    title: 'Queimadura Térmica Extensa',
    theme: 'Cirurgia Plástica / Emergência',
    date: '2026-06-08',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Trabalhador atinge 35% de superfície corporal queimada em acidente com chamas.',
    learningObjectives: ['Calcular área queimada (Regra dos 9).', 'Fórmula de Parkland para ressuscitação volêmica.'],
    teacherInstructions: 'Abordagem do trauma e vias aéreas.',
    status: 'planejado',
  },
  {
    id: 'case_w18_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 18,
    unit: 2,
    title: 'Ressuscitação Volêmica e Curativos no Grande Queimado',
    theme: 'Cirurgia do Trauma',
    date: '2026-06-10',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Fechamento sobre diurese alvo no grande queimado, escarotomias descompressivas e curativos com sulfadiazina.',
    learningObjectives: [
      'Monitorar a resposta volêmica através da débito urinário horário.',
      'Identificar síndrome compartimental e necessidade de escarotomia.',
      'Prevenir sepse de foco cutâneo em centro de queimados.',
    ],
    teacherInstructions: 'Focar no cálculo de Parkland e débito urinário.',
    status: 'planejado',
  },

  {
    id: 'case_w19',
    caseNumber: 1,
    problemNumber: 1,
    week: 19,
    unit: 2,
    title: 'Choque Anafilático em Criança',
    theme: 'Alergologia / Emergência Pediátrica',
    date: '2026-06-15',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Criança apresenta estridor, placas urticariformes e hipotensão 15 minutos após comer amendoim.',
    learningObjectives: ['Mecanismos do choque anafilático mediado por IgE.', 'Uso da Adrenalina intramuscular imediata.'],
    teacherInstructions: 'Cultura de segurança alimentar.',
    status: 'planejado',
  },
  {
    id: 'case_w19_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 19,
    unit: 2,
    title: 'Manejo Anafilático e Plano de Autoinjeção',
    theme: 'Imunologia Clínica / Emergência',
    date: '2026-06-17',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Doses de adrenalina (1:1000 IM na coxa), reação anafilática bifásica, prescrição de autoinjetores e orientações escolares.',
    learningObjectives: [
      'Prescrever a dose exata de adrenalina por peso (0,01 mg/kg).',
      'Manter observação clínica para prevenir anafilaxia bifásica.',
      'Treinar a família no uso de autoinjetores.',
    ],
    teacherInstructions: 'Demonstrar técnica de aplicação de adrenalina.',
    status: 'planejado',
  },

  {
    id: 'case_w20',
    caseNumber: 1,
    problemNumber: 1,
    week: 20,
    unit: 2,
    title: 'SÍNTESE FINAL DO SEMESTRE - Caso Integrativo 1',
    theme: 'Fechamento do Semestre APG',
    date: '2026-06-22',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Sessão final de fechamento longitudinal e consolidação das notas das Unidades 1 e 2.',
    learningObjectives: ['Consolidação do conhecimento.', 'Autoavaliação e feedback geral.'],
    teacherInstructions: 'Conclusão das avaliações do semestre.',
    status: 'planejado',
  },
  {
    id: 'case_w20_s2',
    caseNumber: 2,
    problemNumber: 2,
    week: 20,
    unit: 2,
    title: 'SÍNTESE FINAL DO SEMESTRE - Caso Integrativo 2',
    theme: 'Encerramento Acadêmico APG',
    date: '2026-06-24',
    time: '08:00',
    room: 'Sala APG 101',
    description: 'Apresentação das médias finais ponderadas (U1 20pts + U2 15pts = 35pts) e devolutiva pedagógica individualizada.',
    learningObjectives: [
      'Analisar a evolução longitudinal das competências atitudinais e cognitivas.',
      'Validar o fechamento de notas no sistema.',
      'Pactuar melhorias para os próximos semestres.',
    ],
    teacherInstructions: 'Fechamento oficial das notas na ata de avaliação.',
    status: 'planejado',
  },
];

// Sample Performance Tags
export const availablePerformanceTags = [
  'Proatividade',
  'Liderança positiva',
  'Raciocínio clínico',
  'Comunicação clara',
  'Escuta ativa',
  'Colaboração',
  'Domínio técnico',
  'Dificuldade de síntese',
  'Baixa participação',
  'Necessita acompanhamento',
];

// Generate mock evaluations for weeks 1 to 12
export const initialEvaluations: Evaluation[] = [
  // Ana Beatris Silva (std_1) - High performer
  {
    id: 'eval_std1_w1',
    studentId: 'std_1',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 1,
    unit: 1,
    caseId: 'case_w1',
    date: '2026-02-09',
    role: 'Coordenador',
    attendance: 'Presente',
    criterionScores: { crit_1: 5.0, crit_2: 4.8, crit_3: 4.9, crit_4: 4.8 },
    totalGrossScore: 19.5,
    performanceTags: ['Liderança positiva', 'Raciocínio clínico', 'Comunicação clara'],
    teacherNotes: 'Conduziu o grupo com maestria.',
    pedagogicalFeedback: 'Ana demonstrou excelente liderança como coordenadora, estimulando a participação de todos.',
    status: 'Concluído',
    updatedAt: '2026-02-09',
  },
  {
    id: 'eval_std1_w2',
    studentId: 'std_1',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 2,
    unit: 1,
    caseId: 'case_w2',
    date: '2026-02-16',
    role: 'Secretário',
    attendance: 'Presente',
    criterionScores: { crit_1: 4.8, crit_2: 5.0, crit_3: 4.7, crit_4: 5.0 },
    totalGrossScore: 19.5,
    performanceTags: ['Domínio técnico', 'Escuta ativa'],
    teacherNotes: 'Sintetizou os objetivos com precisão.',
    pedagogicalFeedback: 'Registrou as hipóteses diagnósticas de forma exemplar no quadro.',
    status: 'Concluído',
    updatedAt: '2026-02-16',
  },
  {
    id: 'eval_std1_w3',
    studentId: 'std_1',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 3,
    unit: 1,
    caseId: 'case_w3',
    date: '2026-02-23',
    role: 'Membro',
    attendance: 'Presente',
    criterionScores: { crit_1: 4.5, crit_2: 4.5, crit_3: 4.8, crit_4: 4.7 },
    totalGrossScore: 18.5,
    performanceTags: ['Proatividade', 'Raciocínio clínico'],
    teacherNotes: 'Contribuições fundamentais no escore de Alvarado.',
    pedagogicalFeedback: 'Ótima sustentação teórica.',
    status: 'Concluído',
    updatedAt: '2026-02-23',
  },
  {
    id: 'eval_std1_w9', // Unit 2
    studentId: 'std_1',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 9,
    unit: 2,
    caseId: 'case_w9',
    date: '2026-04-06',
    role: 'Coordenador',
    attendance: 'Presente',
    criterionScores: { crit_1: 5.0, crit_2: 4.8, crit_3: 5.0, crit_4: 4.7 },
    totalGrossScore: 19.5,
    performanceTags: ['Liderança positiva', 'Domínio técnico'],
    teacherNotes: 'Excelente início de 2ª Unidade.',
    pedagogicalFeedback: 'Início da 2ª Unidade impecável.',
    status: 'Concluído',
    updatedAt: '2026-04-06',
  },

  // Bruno Gabriel Oliveira (std_2) - Solid student
  {
    id: 'eval_std2_w1',
    studentId: 'std_2',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 1,
    unit: 1,
    caseId: 'case_w1',
    date: '2026-02-09',
    role: 'Membro',
    attendance: 'Presente',
    criterionScores: { crit_1: 4.0, crit_2: 4.5, crit_3: 4.0, crit_4: 4.0 },
    totalGrossScore: 16.5,
    performanceTags: ['Colaboração', 'Escuta ativa'],
    teacherNotes: 'Participativo e respeitoso.',
    pedagogicalFeedback: 'Boa postura colaborativa.',
    status: 'Concluído',
    updatedAt: '2026-02-09',
  },
  {
    id: 'eval_std2_w2',
    studentId: 'std_2',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 2,
    unit: 1,
    caseId: 'case_w2',
    date: '2026-02-16',
    role: 'Coordenador',
    attendance: 'Presente',
    criterionScores: { crit_1: 4.2, crit_2: 4.0, crit_3: 4.5, crit_4: 4.3 },
    totalGrossScore: 17.0,
    performanceTags: ['Comunicação clara'],
    teacherNotes: 'Boa coordenação do tempo.',
    pedagogicalFeedback: 'Gerenciou o tempo adequadamente.',
    status: 'Concluído',
    updatedAt: '2026-02-16',
  },

  // Carla Vasconcelos (std_3) - Needs attention / Struggling with synthesis
  {
    id: 'eval_std3_w1',
    studentId: 'std_3',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 1,
    unit: 1,
    caseId: 'case_w1',
    date: '2026-02-09',
    role: 'Secretário',
    attendance: 'Presente',
    criterionScores: { crit_1: 3.5, crit_2: 3.5, crit_3: 3.0, crit_4: 2.5 },
    totalGrossScore: 12.5,
    performanceTags: ['Dificuldade de síntese', 'Necessita acompanhamento'],
    teacherNotes: 'Dificuldade para sintetizar os objetivos de aprendizagem.',
    pedagogicalFeedback: 'Precisa melhorar a objetividade na síntese final do caso.',
    status: 'Concluído',
    updatedAt: '2026-02-09',
  },
  {
    id: 'eval_std3_w2',
    studentId: 'std_3',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 2,
    unit: 1,
    caseId: 'case_w2',
    date: '2026-02-16',
    role: 'Membro',
    attendance: 'Ausente', // Absent without certificate -> 0 score
    criterionScores: { crit_1: 0, crit_2: 0, crit_3: 0, crit_4: 0 },
    totalGrossScore: 0.0,
    performanceTags: ['Baixa participação'],
    teacherNotes: 'Falta sem justificativa enviada.',
    pedagogicalFeedback: 'Ausência registrada.',
    status: 'Concluído',
    updatedAt: '2026-02-16',
  },
  {
    id: 'eval_std3_w3',
    studentId: 'std_3',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 3,
    unit: 1,
    caseId: 'case_w3',
    date: '2026-02-23',
    role: 'Membro',
    attendance: 'Atestado', // Medical cert -> excluded from denominator
    criterionScores: { crit_1: 0, crit_2: 0, crit_3: 0, crit_4: 0 },
    totalGrossScore: 0.0,
    performanceTags: [],
    teacherNotes: 'Atestado médico de 3 dias apresentado.',
    pedagogicalFeedback: 'Atestado válido homologado.',
    status: 'Concluído',
    updatedAt: '2026-02-23',
  },

  // Henrique Alves (std_8) - Absenteeism issues
  {
    id: 'eval_std8_w1',
    studentId: 'std_8',
    classId: 'cls_med_1',
    groupId: 'grp_b',
    week: 1,
    unit: 1,
    caseId: 'case_w1',
    date: '2026-02-09',
    role: 'Membro',
    attendance: 'Ausente',
    criterionScores: { crit_1: 0, crit_2: 0, crit_3: 0, crit_4: 0 },
    totalGrossScore: 0.0,
    performanceTags: ['Baixa participação', 'Necessita acompanhamento'],
    teacherNotes: 'Falta sem justificativa.',
    pedagogicalFeedback: 'Aviso enviado referente a falta não justificada.',
    status: 'Concluído',
    updatedAt: '2026-02-09',
  },
  {
    id: 'eval_std8_w2',
    studentId: 'std_8',
    classId: 'cls_med_1',
    groupId: 'grp_b',
    week: 2,
    unit: 1,
    caseId: 'case_w2',
    date: '2026-02-16',
    role: 'Membro',
    attendance: 'Presente',
    criterionScores: { crit_1: 3.5, crit_2: 3.0, crit_3: 3.5, crit_4: 3.0 },
    totalGrossScore: 13.0,
    performanceTags: ['Colaboração'],
    teacherNotes: 'Retorno após falta.',
    pedagogicalFeedback: 'Incentivado a manter regularidade.',
    status: 'Concluído',
    updatedAt: '2026-02-16',
  },

  // Pending evaluation example for Week 12
  {
    id: 'eval_std4_w12',
    studentId: 'std_4',
    classId: 'cls_med_1',
    groupId: 'grp_a',
    week: 12,
    unit: 2,
    caseId: 'case_w12',
    date: '2026-04-27',
    role: 'Secretário',
    attendance: 'Presente',
    criterionScores: { crit_1: 4.0, crit_2: 4.0, crit_3: 0, crit_4: 0 },
    totalGrossScore: 8.0,
    performanceTags: [],
    teacherNotes: 'Aguardando parecer final.',
    pedagogicalFeedback: '',
    status: 'Pendente',
    updatedAt: '2026-04-27',
  },
];

export const initialSettings: AppSettings = {
  institution: 'Faculdade de Medicina - Universidade Federal de Ensino Médico',
  course: 'Bacharelado em Medicina - Módulo APG & Tutoria',
  responsibleTeacher: 'Docente não identificado',
  currentSemester: '2026.1',
  baremaCriteria: initialBaremaCriteria,
  maxBaremaScore: 20,
  maxStudentsPerGroup: 10,
  absencePolicy: 'Faltas sem atestado recebem nota zero e reduzem a média ponderada.',
  certificatePolicy: 'Atestado gera pendência de segunda chamada; a nota somente é registrada após a reposição.',
  lowScoreAlertThreshold: 14.0,
  maxAbsencesAlertThreshold: 2,
};
